---

- name: Install php-fpm
  apt: name=php5-fpm state=latest update_cache=true
  tags:
    - webserver
    - php
    - php-fpm

- name: Install php-cli
  apt: name=php5-cli state=latest update_cache=true
  tags:
    - webserver
    - php
    - php-cli

- name: Install php packages
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - php5-common
    - php5-curl 
    - php5-dev 
    - php5-gd 
    - php5-imagick 
    - php5-mcrypt 
    - php5-memcache 
    - php5-mysql 
    - php5-mongo
    - php5-pspell 
    - php5-snmp 
    - php5-sqlite 
    - php5-xmlrpc 
    - php5-xsl 
    - php-pear 
    - libssh2-php
  tags: 
    - webserver
    - php
    - php-cli

- name: Remove php-cli configuration
  command: mv /etc/php5/cli/php.ini /etc/php5/cli/php.ini.basic
  args:
    removes: /etc/php5/cli/php.ini
  tags:
    - webserver
    - php
    - php-cli

- name: Link php-cli to php-fpm configuration
  command: ln -s /etc/php5/fpm/php.ini /etc/php5/cli/php.ini
  args:
    creates: /etc/php5/cli/php.ini
  tags:
    - webserver
    - php
    - php-cli

- name: Active mongo extension
  copy: src=mongo.ini dest=/etc/php.d/
  ignore_errors: yes
  notify: restart php-fpm
  tags:
    - mongodb
    - php